-- Sahafi Colony Portal — one-time data migration from the community's Excel records
--
-- Run this in the Supabase SQL Editor AFTER schema.sql has been applied.
--
-- Sources:
--   - Sahafi_Colony_E_Block_Monthly_Accounts.xlsx: a single-period snapshot of all
--     130 houses (Paid/Pending + amount), and 5 real entries in its Expense Log sheet.
--     The sheet carries no date/period of its own; per the project owner, this
--     snapshot represents September 2026.
--   - for_work_E_block_list.xlsx, sheet "shafi catalogue e block": 31 residents who've
--     shared name/occupation/blood group. Its other three tabs (personal loan notes,
--     a wedding budget) are unrelated to the community fund and were not imported.
--
-- Safe to re-run: residents upsert by (block, house_number); collections/expenses
-- rows are only inserted if an identical row doesn't already exist.

-- ============================================================================
-- Residents directory: 130 houses (4 of them vacant plots: E-81–E-84),
-- enriched with name/occupation/blood group for the 30 houses in the catalogue.
-- ============================================================================

insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '1', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '2', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '3', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '4', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '5', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '6', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '7', 'Muhammad Rasheed', 'Businessman', 'O+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '8', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '9', 'Muhammad imran', 'Distributor of sharkarganj Foods Ltd', 'B+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '10', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '11', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '12', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '13', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '14', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '15', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '16', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '17', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '18', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '19', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '20', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '21', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '22', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '23', 'IJAZ AHMED FARYAD AHMAD KHAN', null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '24', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '25', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '26', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '27', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '28', 'Adnan imran', null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '29', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '30', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '31', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '32', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '33', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '34', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '35', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '36', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '37', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '38', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '39', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '40', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '41', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '42', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '43', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '44', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '45', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '46', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '47', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '48', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '49', 'Mian shahid shafi', 'BIKE ATO PARTS MACLOAD ROAD', 'A+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '50', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '51', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '52', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '53', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '54', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '55', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '56', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '57', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '58', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '59', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '60', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '61', 'Masood Kamal', null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '62', 'Zill e Rehani Khan', 'Retired from Government Services', null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '63', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '64', 'Sh Humayun zaheer', 'Business man', null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '65', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '66', 'Asad Mahood / Tariq mahmood', 'Mechanical Engineer working as GM operations in german orgnisation / Professor of Islamic Studies', 'B-', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '67', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '68', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '69', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '70', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '71', 'Joudat shah', 'inspector wasa revenue department', null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '72', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '73', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '74', 'DR ABDUL LATIF MIR', 'Pain management consultant', 'A+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '75', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '76', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '77', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '78', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '79', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '80', 'Sayed Mansoor Hussain Bokhari', 'Journalist', 'A+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '81', null, null, null, true) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '82', null, null, null, true) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '83', null, null, null, true) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '84', 'Name Pervaiz Khan', 'Retired as Registrar', 'AB+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '85', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '86', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '87', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '88', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '89', 'Qasim ahsan alvi', 'Rent a car or cable network', null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '90', 'Muhammad Usman', null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '91', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '92', 'Dr. Mehak Zaheer', 'Ultrasound specialist and Gynaecologist', 'B+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '93', 'Ashfaq ahmed mayo', 'advocate', null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '94', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '95', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '96', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '97', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '98', 'Syed Hassan Abbas', 'Software Engineer', 'O+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '99', 'Abdul Wahab Khan', 'Refrigeration and Air Condition Technician', 'B+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '100', 'SALMAN', 'Business of fabric', 'B+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '101', 'Zahid Amir Baig', 'Journalist', 'B+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '102', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '103', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '104', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '105', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '106', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '107', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '108', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '109', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '110', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '111', 'Muhammad Nauman Dar', 'MPhil (CS)
Assistant Registrar, Lahore High Court', 'B-', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '112', 'Zahoor ul haq', null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '113', 'Salman', null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '114', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '115', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '116', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '117', 'M.Sarfraz', 'PAF retired', 'A+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '118', 'Waseem niaz', 'Express News 
President Association photo journalist of Lahore', 'B+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '119', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '120', 'Ahmad Abdullah', 'Agricultural gardening Machinery and generatots/solar/lithium batteries etc', 'A+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '121', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '122', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '123', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '124', 'Hussain Mehdi(Zain)', 'Private job', 'A+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '125', 'Muhammad Imran ahmad', 'College professor of Mathematics(O & A levels & iB)', 'A+', false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '126', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '127', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '128', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '129', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();
insert into public.residents (block, house_number, name, occupation, blood_group, is_vacant) values ('E', '130', null, null, null, false) on conflict (block, house_number) do update set name = coalesce(excluded.name, public.residents.name), occupation = coalesce(excluded.occupation, public.residents.occupation), blood_group = coalesce(excluded.blood_group, public.residents.blood_group), is_vacant = excluded.is_vacant, updated_at = now();

-- ============================================================================
-- Collections: 50 houses marked "Paid" in the snapshot — imported as
-- September 2026 (period_month=9, period_year=2026). recorded_by is left null
-- (nobody in the app recorded these — they're an import from the Excel ledger).
-- ============================================================================

insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '2', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '2' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '3', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '3' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '4', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '4' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '6', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '6' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '7', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '7' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '8', 2000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '8' and c.period_month = 9 and c.period_year = 2026 and c.amount = 2000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '9', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '9' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '11', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '11' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '14', 2000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '14' and c.period_month = 9 and c.period_year = 2026 and c.amount = 2000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '23', 2000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '23' and c.period_month = 9 and c.period_year = 2026 and c.amount = 2000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '28', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '28' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '29', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '29' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '39', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '39' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '43', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '43' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '44', 500, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '44' and c.period_month = 9 and c.period_year = 2026 and c.amount = 500);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '49', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '49' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '50', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '50' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '51', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '51' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '53', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '53' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '55', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '55' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '56', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '56' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '61', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '61' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '62', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '62' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '66', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '66' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '67', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '67' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '72', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '72' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '74', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '74' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '77', 1500, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '77' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1500);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '79', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '79' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '80', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '80' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '85', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '85' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '88', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '88' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '89', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '89' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '90', 1500, 9, 2026, '1000+500' where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '90' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1500);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '91', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '91' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '92', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '92' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '93', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '93' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '98', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '98' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '99', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '99' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '100', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '100' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '101', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '101' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '111', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '111' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '112', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '112' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '113', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '113' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '114', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '114' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '117', 500, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '117' and c.period_month = 9 and c.period_year = 2026 and c.amount = 500);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '118', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '118' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '119', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '119' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '120', 2000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '120' and c.period_month = 9 and c.period_year = 2026 and c.amount = 2000);
insert into public.collections (block, house_number, amount, period_month, period_year, note) select 'E', '125', 1000, 9, 2026, null where not exists (select 1 from public.collections c where c.block = 'E' and c.house_number = '125' and c.period_month = 9 and c.period_year = 2026 and c.amount = 1000);

-- ============================================================================
-- Expenses: 5 real entries already in the file's Expense Log sheet
-- (streetlight repair project). Only the first row has an explicit date
-- (2026-08-15); the other four are clearly the same batch of work, so the same
-- date is used for all five. "Paid by" is preserved in the note field.
-- ============================================================================

insert into public.expenses (description, category, amount, expense_date, note) select 'LIGHTS FROM LIGHT HOUSE', 'streetlights', 50800, date '2026-08-15', 'Paid by MIRZA SAB' where not exists (select 1 from public.expenses e where e.description = 'LIGHTS FROM LIGHT HOUSE' and e.amount = 50800 and e.expense_date = date '2026-08-15');
insert into public.expenses (description, category, amount, expense_date, note) select 'LABOUR FOR LIGHTS', 'streetlights', 11000, date '2026-08-15', 'Paid by MIRZA SAB' where not exists (select 1 from public.expenses e where e.description = 'LABOUR FOR LIGHTS' and e.amount = 11000 and e.expense_date = date '2026-08-15');
insert into public.expenses (description, category, amount, expense_date, note) select 'WIRE FOR LIGHTS', 'streetlights', 3000, date '2026-08-15', 'Paid by MIRZA SAB' where not exists (select 1 from public.expenses e where e.description = 'WIRE FOR LIGHTS' and e.amount = 3000 and e.expense_date = date '2026-08-15');
insert into public.expenses (description, category, amount, expense_date, note) select 'SWITCHES', 'streetlights', 600, date '2026-08-15', 'Paid by MIRZA SAB' where not exists (select 1 from public.expenses e where e.description = 'SWITCHES' and e.amount = 600 and e.expense_date = date '2026-08-15');
insert into public.expenses (description, category, amount, expense_date, note) select 'WIRE AND TAPE', 'streetlights', 1000, date '2026-08-15', 'Paid by MIRZA SAB' where not exists (select 1 from public.expenses e where e.description = 'WIRE AND TAPE' and e.amount = 1000 and e.expense_date = date '2026-08-15');
